export VISUAL="emacsclient -c -a ''"
export EDITOR="$VISUAL"
export EMACS_SERVER_FILE="$HOME/.emacs.d/server"
export LESS="-iMQRSW"
export PYTHONSTARTUP="$HOME/.pythonrc.py"
export PATH="/usr/local/bin:$PATH"
